create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password text,
  dob text,
  provider text not null check (provider in ('local', 'google')),
  google_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pdf_uploads (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  original_name text not null,
  storage_path text not null,
  public_url text not null,
  mime_type text,
  size_bytes bigint,
  extracted_text text,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_analyses (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  pdf_upload_id bigint references public.pdf_uploads(id) on delete set null,
  source text not null check (source in ('pdf', 'manual')),
  exam_type text not null,
  input_payload jsonb,
  result_payload jsonb,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.pdf_uploads enable row level security;
alter table public.ai_analyses enable row level security;

-- O backend usa SUPABASE_SECRET_KEY ou SUPABASE_SERVICE_ROLE_KEY, que ignora RLS.
-- Nao exponha essa chave no app mobile. Se futuramente o app acessar o Supabase
-- diretamente com usuarios autenticados, crie policies por auth.uid().

insert into storage.buckets (id, name, public)
values ('bioapp-pdfs', 'bioapp-pdfs', true)
on conflict (id) do update set public = excluded.public;
